language: cpp

env:
  global:
    - secure: gFJsmma5duxLv+bcn5Qvq6M9r3w0XZZ/GVlolSX3t3rlyqyGwEiN71F7+8Rtv+pzgUaMELKuA8JO+x6ZpOCnMCa/RB/TV6KJrZ31UPfV7BJjt6QzWWPMlkT+3i+pM3PUVoN1zTojz+SE9pMhyILeIx+23S/8mHGXmmIW1Es001I=
    - secure: Sb3uSRvYdqEnh9sQngr5W+WbrodlZjW7cIg2ZAECj1IabZc4rn4Xp4+vmLiCjRCl5p6idL515ELLG4OYv5joqM/XtY7mIzCbHkaxs81+3PBroGezgW6gxWqLDtwoI76aonk3QHkD38L2uMKhZADUxK3K4l9fmauSrivz2TPU6Rw=

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update;

install:
  - .travis_scripts/boost.sh
  - if [ "$CXX" == "clang++" ]; then .travis_scripts/clang.sh; fi
  - if [ "$CXX" == "g++"     ]; then .travis_scripts/gcc.sh; fi

script:
  - mkdir build; pushd build;
  - cmake -D CMAKE_CXX_FLAGS=--coverage .. && make debug && make -j 2 run_test
  - popd;

after_success:
  - .travis_scripts/update_website_dox.sh 
  - .travis_scripts/coveralls.sh
